export interface ServiceInfo {
  id: string;
  category: string;
  displayName: string;
  price: number;
  min: number;
  max: number;
  apiProvider?: string;
}

export const servicesMap: ServiceInfo[] = [
  { id: "5009", category: "📷[인스타] 📍인기게시물 상위노출📍", displayName: "상위노출용 좋아요+도달", price: 24, min: 100, max: 10000, apiProvider: "smmkings" },
  { id: "5992", category: "📷[인스타] 🇰🇷한국인 팔로워", displayName: "한국인 팔로워 [알뜰]", price: 26, min: 10, max: 5000, apiProvider: "smmkings" },
  { id: "5165", category: "📷[인스타] 🇰🇷한국인 팔로워", displayName: "고퀄 한국인 팔로워", price: 32, min: 1, max: 15000, apiProvider: "smmkings" },
  { id: "5241", category: "📷[인스타] 🇰🇷한국인 팔로워", displayName: "한국인 실사용자 팔로워", price: 120, min: 5, max: 40000, apiProvider: "smmkings" },
  { id: "5302", category: "📷[인스타] 🇰🇷한국인 좋아요", displayName: "🇰🇷한국인 좋아요(+노출)", price: 3, min: 10, max: 5000, apiProvider: "smmkings" },
  { id: "3263", category: "📷[인스타] 🇰🇷한국인 좋아요", displayName: "🇰🇷실제 한국인 좋아요", price: 10, min: 5, max: 20000, apiProvider: "smmkings" },
  { id: "5300", category: "📷[인스타] 🇰🇷한국인 좋아요", displayName: "🇰🇷고퀄리티 한국인 좋아요", price: 4.5, min: 1, max: 10000, apiProvider: "smmkings" },
  { id: "5249", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 랜덤 댓글", price: 100, min: 2, max: 100, apiProvider: "smmkings" },
  { id: "5794", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 남성 랜덤 댓글", price: 82, min: 2, max: 100, apiProvider: "smmkings" },
  { id: "5795", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 여성 랜덤 댓글", price: 82, min: 1, max: 100, apiProvider: "smmkings" },
  { id: "5796", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 커스텀 댓글", price: 82, min: 1, max: 100, apiProvider: "smmkings" },
  { id: "5797", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 남성 커스텀 댓글", price: 82, min: 1, max: 100, apiProvider: "smmkings" },
  { id: "5798", category: "📷[인스타] 🇰🇷한국인 댓글", displayName: "🇰🇷한국인 여성 커스텀 댓글", price: 82, min: 1, max: 100, apiProvider: "smmkings" },
  { id: "3777", category: "📷[인스타] 가성비 외국인 팔로워", displayName: "🌐실제 외국인 팔로워", price: 15, min: 50, max: 500000, apiProvider: "smmkings" },
  { id: "4711", category: "📷[인스타] 가성비 외국인 팔로워", displayName: "🌐알뜰 외국인 팔로워", price: 5, min: 20, max: 500000, apiProvider: "smmkings" },
  { id: "2849", category: "📷[인스타] 가성비 외국인 좋아요", displayName: "🌐고품질 외국인 좋아요", price: 1, min: 10, max: 300000, apiProvider: "smmkings" },
  { id: "2985", category: "📷[인스타] 가성비 외국인 좋아요", displayName: "🌐일반 외국인 좋아요", price: 0.5, min: 10, max: 500000, apiProvider: "smmkings" },
  { id: "2809", category: "📷[인스타] 가성비 외국인 좋아요", displayName: "🌐유령 외국인 좋아요", price: 0.3, min: 10, max: 500000, apiProvider: "smmkings" },
  { id: "5226", category: "📷[인스타] 릴스 서비스", displayName: "🇰🇷한국인 릴스 조회수", price: 1, min: 500, max: 2000000, apiProvider: "smmkings" },
  { id: "5266", category: "📷[인스타] 릴스 서비스", displayName: "🌐일반 외국인 좋아요", price: 0.1, min: 100, max: 100000000, apiProvider: "smmkings" },
  { id: "3921", category: "📷[인스타] 노출/도달/저장/공유", displayName: "게시물 저장", price: 1, min: 50, max: 4000, apiProvider: "smmkings" },
  { id: "6290", category: "📷[인스타] 노출/도달/저장/공유", displayName: "게시물 & 릴스 공유", price: 1, min: 10, max: 1000000, apiProvider: "smmkings" },
  { id: "4308", category: "📷[인스타] 노출/도달/저장/공유", displayName: "노출 + 도달", price: 0.5, min: 10 , max: 1000000, apiProvider: "smmkings" },
  { id: "2875", category: "📷[인스타] 노출/도달/저장/공유", displayName: "노출 + 도달 + 게시물방문", price: 1, min: 100, max: 5000000, apiProvider: "smmkings" },
  { id: "4540", category: "▶︎[유튜브] 좋아요 & 댓글", displayName: "🇰🇷유튜브 한국인 좋아요", price: 30, min: 10, max: 1000000, apiProvider: "smmkings" },
  { id: "1287", category: "▶︎[유튜브] 좋아요 & 댓글", displayName: "유튜브 실계정 좋아요", price: 30, min: 10, max: 10000, apiProvider: "smmkings" },
  { id: "4422", category: "▶︎[유튜브] 좋아요 & 댓글", displayName: "🇰🇷한국인 댓글", price: 150, min: 10, max: 85, apiProvider: "smmkings" },
  { id: "4574", category: "▶︎[유튜브] 구독자", displayName: "유튜브 고퀄 구독", price: 20, min: 100, max: 50000, apiProvider: "smmkings" },
  { id: "2794", category: "▶︎[유튜브] 구독자", displayName: "유튜브 알뜰 구독", price: 14, min: 50, max: 100000, apiProvider: "smmkings" },
  { id: "4820", category: "📖[페이스북] 한국인 게시물 좋아요", displayName: "🇰🇷한국인 게시물 좋아요", price: 44, min: 5, max: 10000, apiProvider: "smmkings" },
  { id: "5765", category: "📖[페이스북] 한국인 게시물 좋아요", displayName: "🇰🇷한국인 여성 게시물 좋아요", price: 44, min: 5, max: 5000, apiProvider: "smmkings" },
  { id: "5766", category: "📖[페이스북] 한국인 게시물 좋아요", displayName: "🇰🇷한국인 남성 게시물 좋아요", price: 44, min: 5, max: 5000, apiProvider: "smmkings" },
  { id: "5769", category: "📖[페이스북] 한국인 댓글", displayName: "🇰🇷한국인 남성 댓글", price: 300, min: 5, max: 5000, apiProvider: "smmkings" },
  { id: "5770", category: "📖[페이스북] 한국인 댓글", displayName: "🇰🇷한국인 여성 댓글", price: 300, min: 5, max: 5000, apiProvider: "smmkings" },
  { id: "4822", category: "📖[페이스북] 한국인 댓글", displayName: "🇰🇷한국인 커스텀 댓글", price: 340, min: 3, max: 1000, apiProvider: "smmkings" },
  { id: "2393", category: "📖[페이스북] 외국인 좋아요", displayName: "🌐외국인 게시물 좋아요", price: 5, min: 100, max: 1000, apiProvider: "smmkings" },
  { id: "3826", category: "[틱톡] 영상 조회수/좋아요/댓글/저장", displayName: "🌐외국인 조회수", price: 0, min: 100, max: 10000000, apiProvider: "smmkings" },
  { id: "4778", category: "[틱톡] 영상 조회수/좋아요/댓글/저장", displayName: "🇰🇷한국인 조회수", price: 0.5, min: 500, max: 5000000, apiProvider: "smmkings" },
  { id: "5060", category: "[틱톡] 영상 조회수/좋아요/댓글/저장", displayName: "고품질 좋아요", price: 1, min: 10, max: 75000, apiProvider: "smmkings" },
  { id: "3997", category: "[틱톡] 영상 조회수/좋아요/댓글/저장", displayName: "실계정 댓글", price: 40, min: 5, max: 10000, apiProvider: "smmkings" },
  { id: "4467", category: "[틱톡] 영상 조회수/좋아요/댓글/저장", displayName: "저장", price: 0.5, min: 10, max: 100000, apiProvider: "smmkings" },
  { id: "5750", category: "[틱톡] 계정 팔로워", displayName: "🌐외국인 팔로워", price: 6, min: 100, max: 700000, apiProvider: "smmkings" },
  { id: "4796", category: "[X(트위터)] 고퀄 종합서비스", displayName: "🇰🇷한국인 게시글 좋아요", price: 13, min: 20, max: 500, apiProvider: "smmkings" },
  { id: "4815", category: "[X(트위터)] 고퀄 종합서비스", displayName: "🌐외국인 팔로워", price: 32, min: 10, max: 100000, apiProvider: "smmkings" },
  { id: "4439", category: "[X(트위터)] 고퀄 종합서비스", displayName: "🌐외국인 게시글 좋아요", price: 3, min: 10, max: 1000000, apiProvider: "smmkings" },
  { id: "4805", category: "[X(트위터)] 고퀄 종합서비스", displayName: "리트윗", price: 5, min: 50, max: 50000, apiProvider: "smmkings" },
  { id: "5206", category: "[X(트위터)] 고퀄 종합서비스", displayName: "영상 조회 + 도달", price: 0.5, min: 500, max: 10000000, apiProvider: "smmkings" },
  { id: "5689", category: "[쓰레드] 한국인 좋아요/팔로워", displayName: "🇰🇷한국인 실제계정 좋아요", price: 20, min: 5, max: 10000, apiProvider: "smmkings" },
  { id: "5690", category: "[쓰레드] 한국인 좋아요/팔로워", displayName: "🇰🇷한국인 실제계정 팔로워", price: 100, min: 5, max: 10000, apiProvider: "smmkings" },
  { id: "3399", category: "🪓신고🪓", displayName: "[틱톡]계정 신고", price: 250, min: 50, max: 3000, apiProvider: "STREAM" },
  { id: "4584", category: "🪓신고🪓", displayName: "[틱톡]영상 신고", price: 260, min: 1, max: 3000, apiProvider: "STREAM" },
  { id: "3612", category: "🪓신고🪓", displayName: "[트위터X]계정 신고", price: 300, min: 100, max: 15000, apiProvider: "STREAM" },
  { id: "3613", category: "🪓신고🪓", displayName: "[트위터X]게시물 신고", price: 300, min: 100, max: 15000, apiProvider: "STREAM" },
  { id: "3619", category: "🪓신고🪓", displayName: "[인스타]계정 신고", price: 300, min: 1, max: 3000, apiProvider: "STREAM" },
  { id: "3620", category: "🪓신고🪓", displayName: "[인스타]영상/릴스 신고", price: 300, min: 1, max: 3000, apiProvider: "STREAM" },
  { id: "3624", category: "🪓신고🪓", displayName: "[유튜브]영상 신고", price: 300, min: 1, max: 3000, apiProvider: "STREAM" },
  { id: "3625", category: "🪓신고🪓", displayName: "[유튜브]채널 신고", price: 300, min: 1, max: 3000, apiProvider: "STREAM" },
  { id: "3625", category: "🪓신고🪓", displayName: "[유튜브]영상 싫어요", price: 10, min: 10, max: 10000, apiProvider: "STREAM" },
  ];
